### ISSUE TITLE
Streamer for OYMotion on windows/mac, compatibility issue

### ISSUE THREAD

**Issue by zubaidah93** [LibEMG/libemg#17]
I am attempting to run the data streamer code on Windows and macOS, but it currently relies on the bluepy library, which is designed for Linux. As a result, I am encountering compatibility issues. Has the code been tested on non-Linux platforms? If not, are there any suggestions for adapting the code to work on Windows and macOS? I can stream using bleak on different code but I would like to use your pipeline of filtering, feature extraction,.. so I think I should be consistent with your communication protocol hence, I need to figure out this part. Thank you.

**Comment by eeddy** [comment]
Hey @zubaidah93 , are you trying to connect to the OyMotion on windows/mac? Or is the issue from the streamer but you are trying to use a different device?

**Comment by zubaidah93** [comment]
I am trying to connect the Oymotion to the windows for example and stream data, however, even though there is an if statement to check in the system platform is linux and import bluepy, however,in  (libemg/_streamers/oymotion_streamer.py) it regardless uses Peripheral() in Gforce class, and other classes imported from bluepy. Question is can I use the pipeline for Oymotion armband with non-linux system? say windows for example. Thanks!

**Comment by eeddy** [comment]
@zubaidah93 Unfortunately, we only have the OyMotion streamer working in Linux. At some point, we are planning to get it working for Windows and Mac. We would also be happy if you were willing to develop the streamer for Windows (and could help if needed).

**Comment by zubaidah93** [comment]
Please find the file attached, that utilizes bleak to connect to the Oymotion and stream data. I hope it can be helpful to use and this will enable the library for both MAC/ Windows platforms. Thanks! 
[oymotion_win_mac_stream.odt](https://github.com/LibEMG/libemg/files/14152618/oymotion_win_mac_stream.odt)

**Comment by eeddy** [comment]
@zubaidah93  I'll try to get this integrated into the library today. Thanks for sharing this!

**Comment by eeddy** [comment]
Hi @zubaidah93, libemg version 0.0.3 should now include compatibility for the OyMotion streamer. Thank you for the source code. We plan to add IMU compatibility to the library in the near future!

**Comment by eeddy** [comment]
https://github.com/LibEMG/libemg/pull/21
