### ISSUE TITLE
Wavelet Feature Extraction Warning

### ISSUE THREAD

**Issue by cbmorrell** [LibEMG/libemg#75]
Extracting the wavelet energy feature group raises this warning: 
`UserWarning: Level value of 7 is too high: all coefficients will experience boundary effects.`

This prints every time `extract_features` is called, which means `stdout` is full of these statements when running a model online. Since this is the default value based on what the paper suggests, we should probably just ignore these.

**Comment by eeddy** [comment]
Closing as this will be fixed by this PR: https://github.com/LibEMG/libemg/pull/85
