### ISSUE TITLE
Divide by zero error in F1 Score calculation and calculation does not take into consideration rejected samples

### ISSUE THREAD

**Issue by lpetrich** [LibEMG/libemg#87]
In the `_get_PREC_helper` method it occasionally throws a divide by zero error on line 299` precision[c] = tp / (tp + fp)`.

You can replicate this by running LDA on participant 16 from the 3DC dataset with a rejection threshold of 0.8 applied. 

I believe the `get_F1` should also ignore rejected samples, just like the `get_CA` method does, otherwise the recall score will drop from the -1 values giving a skewed F-score calculation.

**Comment by ECEEvanCampbell** [comment]
I agree that it makes sense that precision should ignore rejected samples, as rejected samples are neither true positive nor false positives. I'll add this issue to the kanban board in the projects tab to be done in the future.

**Comment by eeddy** [comment]
This will be fixed by: https://github.com/LibEMG/libemg/pull/85
