### ISSUE TITLE
Cannot find CollectDataController.py 

### ISSUE THREAD

**Issue by gjmm07** [LibEMG/libemg#95]
Hi everyone, 

in [_delsys_API_streamer](https://github.com/LibEMG/libemg/blob/main/libemg/_streamers/_delsys_API_streamer.py) it says in the doc-string, See CollectDataController.py for usage example. 
Where can I find the file? Has it been renamed? 

I tried this: 
```
from libemg.streamers import delsys_api_streamer
key = "abc"
license_ = "xyz"
streamer, shared_memory = delsys_api_streamer(key, license_)
streamer.connect(key, license_)
```
But I get an attribute error: no attribute 'trigbase' 

Thanks in advance.

**Comment by cbmorrell** [comment]
Hi @gjmm07 - thanks for bringing this to our attention. I believe the docstring in that file is from the Delsys library files, and we must have forgotten to delete it. We don't have a `CollectDataController.py` usage example on our end.


In terms of the `AttributeError` are you getting it when calling `streamer.connect` or `delsys_api_streamer`? `delsys_api_streamer` automatically starts the process and connects to the device for you, so you shouldn't need to call `.connect` yourself. The `trigbase` field is instantiated in the `.run` method, so if you call `.connect` in the main thread you'll get an `AttributeError`. I would recommend deleting the last line and trying from there. Please let us know if you're getting an error in `delsys_api_streamer` and we can help with debugging.

**Comment by gjmm07** [comment]
Hello @cbmorrell 
thanks for the quick reply. I have gotten the error later when calling the "connect"-method. Running the "delsys_api_streamer" yields no errors. Is there a minimal example for using delsys? All examples seem to use different streamers. 
I tried to continue, but the streamer seems to not be connected: 
```
from libemg.streamers import delsys_api_streamer
from libemg.data_handler import OnlineDataHandler

key="abc"
license_ = "xyz"

streamer, shared_memory = delsys_api_streamer(key, license_)
print(streamer.connected)
odh = OnlineDataHandler(shared_memory)
```
streamer.connected returns False and the last line returns errors in OnlineDataHandler.prepare_smm

**Comment by cbmorrell** [comment]
@gjmm07 That's good to hear - you shouldn't have to call the `connect` method because we call that for you. The `connected` field doesn't ever actually get used, so I'm guessing it's just a symptom of being pasted from the Delsys files. What is the error you get when instantiating the `OnlineDataHandler`?

**Comment by gjmm07** [comment]
@cbmorrell I get the following error: 
```
Traceback (most recent call last):
  File "C:\Users\Finn\Documents\Python Scripts\libemg_test\test.py", line 9, in <module>
    odh = OnlineDataHandler(shared_memory)
  File "C:\Users\Finn\Anaconda3\envs\libemg\lib\site-packages\libemg\data_handler.py", line 542, in __init__
    self.prepare_smm()
  File "C:\Users\Finn\Anaconda3\envs\libemg\lib\site-packages\libemg\data_handler.py", line 552, in prepare_smm
    while not self.smm.find_variable(*i):
  File "C:\Users\Finn\Anaconda3\envs\libemg\lib\site-packages\libemg\shared_memory_manager.py", line 32, in find_variable
    smh = SharedMemory(tag, size=int(type().itemsize * np.prod(shape)))
  File "C:\Users\Finn\Anaconda3\envs\libemg\lib\site-packages\numpy\core\fromnumeric.py", line 3100, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "C:\Users\Finn\Anaconda3\envs\libemg\lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

I checked, shape a tuple (5300, None) which causes errors in np.prod. 
Thanks

**Comment by cbmorrell** [comment]
@gjmm07 Okay I see the issue now. We expect that you either pass in `num_channels` or `shared_memory_items` to the `delsys_api_streamer`, so since they aren't passed here they're both defaulted to `None`. We use `num_channels` to make shared memory items if you don't pass them in, so it's trying to make a shared memory instance of size `None`. We don't explain this in the docstring or have a check for this, so I'll modify that. If you use this code it should work:

```Python
from libemg.streamers import delsys_api_streamer
from libemg.data_handler import OnlineDataHandler

key="abc"
license_ = "xyz"

streamer, shared_memory = delsys_api_streamer(key, license_, num_channels=4)    # set your desired number of Delsys sensors
odh = OnlineDataHandler(shared_memory)
```

**Comment by eeddy** [comment]
Closing as this was addressed in https://github.com/LibEMG/libemg/commit/8e6ad119337c932a8b1e3f720868e5f347bb944f#diff-06582e09a3bce5c09466791365ebe4a6e7b43ac5de75f30991029079f405726cR402
